services:

  pg:
    container_name: pg_name
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=patres
    image: postgres:14.15-alpine3.21
    volumes:
      - ./pgdata:/var/lib/postgresql/data