"""add in table books CheckConstraint and in handing_books_users column amount

Revision ID: 2b205cb9b097
Revises: 1cae33cedb2c
Create Date: 2025-01-30 20:07:40.337337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b205cb9b097"
down_revision: Union[str, None] = "1cae33cedb2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_book", "books", ["title", "author"])
    op.create_check_constraint("check_amount", "books", 'amount >= 0')
    op.add_column(
        "handing_books_users",
        sa.Column("amount", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("handing_books_users", "amount")
    op.drop_constraint("uq_book", "books", type_="unique")
    op.drop_constraint("check_amount", "books", type_="check")
    # ### end Alembic commands ###
